spring.application.name=Reclamation
spring.data.mongodb.uri=mongodb+srv://sarrahamoudi00:223JFT3784@reclamation.2vm7lcx.mongodb.net/?retryWrites=true&w=majority&appName=Reclamation
spring.data.mongodb.database=Reclamation
server.port=8083
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Secret clé
application.security.jwt.secret-key=SR72aaIRCzXl7ohXLVsM_vegwD7h-6DT1jerbJwTtI4=
application.security.jwt.expiration=86400000

spring.mail.host=smtp.zoho.com
spring.mail.port=587
spring.mail.username=noreply@maginater.com
spring.mail.password=Test1234,azert
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.enable=true
# Jakarta Mail Debug Logging
logging.level.jakarta.mail=DEBUG

spring.profiles.active=dev
application.mailing.frontend.activation-url=http://localhost:4200/activate-account
# application.properties
reset.password.url=http://localhost:4200/reset-password

